name: Deploy to VPS

on:
  push:
    branches:
      - main   # Auto deploy kalau ada push ke branch main
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy source code to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/root/project/E-Recruitment-Laravel-Admin"

      - name: Run docker compose on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/project/E-Recruitment-Laravel-Admin
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            docker system prune -af --volumes
